version: '3.9'
services:
  user-management-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: postgres:13.4
    environment:
      POSTGRES_DB: user-management-db
      POSTGRES_USER: user-management-service
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
